<x-app-layout>
    <x-slot name="header"><div><h2 class="text-xl font-semibold text-gray-900">Cierre de caja</h2><p class="text-sm text-gray-500">{{ $activeBusiness->name }}</p></div></x-slot>
    <div class="py-8"><div class="mx-auto flex max-w-6xl flex-col gap-6 px-4 sm:px-6 lg:px-8">
        @if (session('status'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-green-800">{{ session('status') }}</div>@endif
        <form method="GET" class="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-5 shadow-sm"><div><label for="date" class="block text-sm font-medium text-gray-700">Fecha de trabajo</label><input id="date" name="date" type="date" value="{{ $selectedDate->format('Y-m-d') }}" max="{{ now()->format('Y-m-d') }}" class="mt-1 rounded-lg border-gray-300" onchange="this.form.submit()"></div><noscript><button class="rounded-lg bg-gray-800 px-4 py-2 text-white">Consultar</button></noscript></form>
        <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div class="rounded-2xl bg-indigo-600 p-5 text-white"><p class="text-sm text-indigo-100">Facturación</p><p class="mt-2 text-3xl font-bold">{{ number_format((float) $summary->total_revenue, 2, ',', '.') }} €</p></div>
            <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-gray-500">Efectivo esperado</p><p class="mt-2 text-3xl font-bold">{{ number_format((float) $summary->expected_cash, 2, ',', '.') }} €</p></div>
            <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-gray-500">Tarjeta</p><p class="mt-2 text-3xl font-bold">{{ number_format((float) $summary->card_revenue, 2, ',', '.') }} €</p></div>
            <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-gray-500">Tickets</p><p class="mt-2 text-3xl font-bold">{{ (int) $summary->ticket_count }}</p></div>
        </section>
        <section class="grid gap-6 lg:grid-cols-[minmax(0,420px)_1fr]">
            <form method="POST" action="{{ route('cash-closures.store') }}" class="flex h-fit flex-col gap-4 rounded-2xl border bg-white p-6 shadow-sm">@csrf<input type="hidden" name="business_date" value="{{ $selectedDate->format('Y-m-d') }}"><div><h3 class="font-bold text-gray-900">{{ $existingClosure ? 'Revisar cierre guardado' : 'Realizar cierre' }}</h3><p class="text-sm text-gray-500">Cuenta el dinero físico e introduce el total.</p></div><div><label for="counted_cash" class="text-sm font-medium text-gray-700">Efectivo contado</label><div class="relative mt-1"><input id="counted_cash" name="counted_cash" type="number" min="0" step="0.01" required value="{{ old('counted_cash', $existingClosure?->counted_cash) }}" class="w-full rounded-lg border-gray-300 pr-10 text-lg font-bold"><span class="absolute right-4 top-3 text-gray-500">€</span></div><x-input-error :messages="$errors->get('counted_cash')" class="mt-2" /></div>@if ($existingClosure)<div class="rounded-lg bg-gray-50 p-4 text-sm"><p>Diferencia guardada: <strong class="{{ (float) $existingClosure->difference === 0.0 ? 'text-green-700' : 'text-red-600' }}">{{ number_format((float) $existingClosure->difference, 2, ',', '.') }} €</strong></p></div>@endif<button class="rounded-xl bg-green-600 px-5 py-3 font-bold text-white hover:bg-green-700">Guardar cierre</button></form>
            <div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h3 class="font-bold">Historial de cierres</h3></div><div class="overflow-x-auto"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr><th class="p-4 text-left">Fecha</th><th class="p-4 text-right">Esperado</th><th class="p-4 text-right">Contado</th><th class="p-4 text-right">Diferencia</th></tr></thead><tbody class="divide-y">@forelse ($closures as $closure)<tr><td class="p-4"><a href="{{ route('cash-closures.index', ['date' => $closure->business_date->format('Y-m-d')]) }}" class="font-semibold text-indigo-600">{{ $closure->business_date->format('d/m/Y') }}</a></td><td class="p-4 text-right">{{ number_format((float) $closure->expected_cash, 2, ',', '.') }} €</td><td class="p-4 text-right">{{ number_format((float) $closure->counted_cash, 2, ',', '.') }} €</td><td class="p-4 text-right font-bold {{ (float) $closure->difference === 0.0 ? 'text-green-700' : 'text-red-600' }}">{{ number_format((float) $closure->difference, 2, ',', '.') }} €</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-gray-500">Todavía no hay cierres guardados.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $closures->links() }}</div></div>
        </section>
    </div></div>
</x-app-layout>
